name: pyoof

channels:
  - astropy

dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - scipy
  - pytest
  - astropy
  - pyyaml
  - sphinx-astropy
  - pytest_astropy_header
  # - pip:
  #   - sphinx-gallery>=0.1.12
  #   - jplephem
