name: pyoof

channels:
  - astropy

dependencies:
  - python>=3.6
  - numpy
  - matplotlib
  - scipy
  - pytest
  - astropy
  - pyyaml
  - sphinx-astropy
  # - pytest_astropy_header # if added docs won't compile
  - pip:
    - sphinx-gallery>=0.7
  #   - jplephem
